name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy code to EC2
      uses: appleboy/scp-action@master
      with:
        host: 18.219.196.154
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/ubuntu/repo"

    - name: SSH to EC2 and build
      uses: appleboy/ssh-action@master
      with:
        host: 18.219.196.154
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/repo
          go build .

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
