name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy code to EC2
      uses: appleboy/scp-action@master
      with:
        host: 18.219.196.154
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/ubuntu/repo"

    - name: SSH to EC2 and build
      env:
        TF_VAR_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      uses: appleboy/ssh-action@master
      with:
        host: 18.219.196.154
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/repo
          echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
          source ~/.bashrc
          export PATH=$PATH:/usr/local/go/bin
          export TF_VAR_AWS_ACCESS_KEY=$TF_VAR_AWS_ACCESS_KEY
          export TF_VAR_AWS_SECRET_KEY=$TF_VAR_AWS_SECRET_KEY
          go get
          go build .
          sudo touch nohupout.out
          chmod 777 nohupout.out
          nohup ./voinc-backend > nohupout.out 2>&1 &

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
